SkillsFundingAgency/das-apim-endpoints

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingGetProviderCourseItemFromMediatorType.cs, src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetProviderCourseItem.cs, src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseProviderListItem.cs, src/SFA.DAS.FindApprenticeshipTraining.Api/Models/ProviderCourseBase.cs, src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCourseProvider/GetTrainingCourseProviderQueryHandler.cs, src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetProviderStandardItem.cs, src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetProvidersListItem.cs
On the Course Providers list, if a provider has a trading name that is different from it's primary name it will be displayed under 'Other Names'
=> FAT2-236 - add_trading_name_providers_list

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Extensions/WhenOrderingByProviderRating.cs, src/SFA.DAS.FindApprenticeshipTraining.Api/Extensions/TrainingCourseProviderOrderByExtension.cs, src/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/TrainingCourses/Queries/WhenGettingProvidersByTrainingCourse.cs, src/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingTheGetProvidersByCourseRequest.cs, src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCourseProviders/GetTrainingCourseProvidersQueryHandler.cs, src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/GetProvidersByCourseRequest.cs
When there is only one percentile value in a range of providers that now gets 4pts. 
When they are tied on score, then the pass rate is also used to determine the order
=> FAT2-316 Provider Ordering Changes

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Controllers/TrainingCourses/WhenCallingGetTrainingCoursesList.cs, src/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/TrainingCoursesController.cs, src/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/TrainingCourses/Queries/WhenGettingTrainingCourseList.cs, src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCoursesList/GetTrainingCoursesListQuery.cs, src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCoursesList/GetTrainingCoursesListQueryHandler.cs
The course search filtering now accepts the name of the sector and looks up the Id from the list of sectors
=> FAT2-334 Change so that it takes name of sector instead of id

azure-pipelines.yml
Updated das-platform-building-blocks tag from 0.2.6 to 0.3.3 and enable PR triggered builds
Dependency Check task will only run on pull request triggered builds
=> Updated das-platform-building-blocks tag from 0.2.6 to 0.3.3 and enable PR triggered builds

src/SFA.DAS.EpaoRegister.Api.UnitTests/Models/GetEpaoCoursesModelTests/WhenCastingGetEpaoCoursesApiModelFromMediatorType.cs, src/SFA.DAS.EpaoRegister.UnitTests/Application/Epaos/Queries/WhenHandlingGetEpaoCoursesQuery.cs, src/SFA.DAS.EpaoRegister/Application/Epaos/Queries/GetEpaoCourses/GetEpaoCoursesQueryHandler.cs
If there are no standards for a provider this was returning a 404 response. now it returns an empty list instead
=> FAT2-403 - Change so that empty list returned instead of 404

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Controllers/TrainingCourses/WhenCallingGetTrainingCourseProvider.cs, src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingGetProviderCourseItemFromMediatorType.cs, src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetProviderCourseItem.cs, src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetProviderStandardItem.cs
Map StandardInfoUrl to outer api response for website instead of contacturl
=> FAT2-416 - Add StandardInfoUrl to inner api response

src/SFA.DAS.Assessors.Api/Models/GetStandardDetailsResponse.cs, src/SFA.DAS.Assessors/InnerApi/Responses/StandardDetailResponse.cs
Following on from this courses api [pull request](https://github.com/SkillsFundingAgency/das-courses-api/pull/84)
I have removed the CoreSkillsCount from Assessors API. There is still an existing CoreSkillsCount field on `SFA.DAS.FindApprenticeshipTraining.InnerApi.Responses.GetStandardsListItem` but this is populated with other data in the courses API response and not from its own field like in the Assessor outer API so I have left as is.
=> SV-528 delete core skills count field

src/SFA.DAS.Approvals.UnitTests/Application/TrainingCourses/Queries/WhenGettingTrainingCourseStandards.cs, src/SFA.DAS.Approvals/Application/TrainingCourses/Queries/GetStandardsQueryHandler.cs, src/SFA.DAS.Assessors.Api/Models/GetCourseListItem.cs, src/SFA.DAS.Assessors.UnitTests/Application/Queries/WhenHandlingGetTrainingCoursesQuery.cs, src/SFA.DAS.Assessors/Application/Queries/GetTrainingCourses/GetTrainingCoursesQuery.cs, src/SFA.DAS.Assessors/Application/Queries/GetTrainingCourses/GetTrainingCoursesQueryHandler.cs, src/SFA.DAS.Assessors/InnerApi/Responses/GetStandardsListItem.cs, src/SFA.DAS.EpaoRegister.UnitTests/Application/Epaos/Queries/WhenHandlingGetEpaoCoursesQuery.cs, src/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/TrainingCourses/Services/WhenGettingCourses.cs, src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Services/CachedCoursesService.cs, src/SFA.DAS.FindEpao.UnitTests/Application/Courses/Queries/GetCourseList/WhenHandlingGetCourseListQuery.cs, src/SFA.DAS.FindEpao.UnitTests/Application/Courses/Services/WhenGettingCourses.cs, src/SFA.DAS.FindEpao/Application/Courses/Queries/GetCourseList/GetCourseListQueryHandler.cs, src/SFA.DAS.FindEpao/Application/Courses/Services/CachedCoursesService.cs, src/SFA.DAS.ManageApprenticeships.UnitTests/Application/Queries/GetStandards/WhenHandlingTheGetStandardsQuery.cs, src/SFA.DAS.ManageApprenticeships/Application/Queries/GetStandards/GetStandardsQueryHandler.cs, src/SFA.DAS.Recruit.UnitTests/Application/Queries/GetTrainingProgrammes/WhenHandlingTheGetTrainingProgrammesQuery.cs, src/SFA.DAS.Recruit/Application/Queries/GetTrainingProgrammes/GetTrainingProgrammesQueryHandler.cs, src/SFA.DAS.SharedOuterApi.UnitTests/InnerApi/Requests/WhenBuildingTheGetAllStandardsListRequest.cs, src/SFA.DAS.SharedOuterApi.UnitTests/InnerApi/Requests/WhenBuildingTheGetAllStandardsRequest.cs, src/SFA.DAS.SharedOuterApi/InnerApi/Requests/GetActiveStandardsListRequest.cs, src/SFA.DAS.SharedOuterApi/InnerApi/Requests/GetAllStandardsRequest.cs
Original PR #299 was already approved and merged into SV-372. However this was required to be separated as it is not going out in the same release as SV-372. 
More work was done which is going out with SV-372, hence had to rebase the branch on top of StandardOptions release branch and reopen the PR. 
I have excluded postman changes as they become too difficult to merge. I will update them in a newer PR once this PR is merged into a release branch.
=> SV-467 Assessor outer API to return all standards

src/SFA.DAS.LevyTransferMatching.Api.UnitTests/Controllers/OpportunityTests/WhenCallingGetApplicationDetails.cs, src/SFA.DAS.LevyTransferMatching.Api/Controllers/OpportunityController.cs, src/SFA.DAS.LevyTransferMatching.Api/Models/PledgeDto.cs, src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/GetStandards/WhenCallingHandle.cs, src/SFA.DAS.LevyTransferMatching/Application/Queries/GetOpportunity/GetOpportunityQueryHandler.cs, src/SFA.DAS.LevyTransferMatching/Application/Queries/Standards/GetStandardsQuery.cs, src/SFA.DAS.LevyTransferMatching/Application/Queries/Standards/GetStandardsQueryHandler.cs, src/SFA.DAS.LevyTransferMatching/Models/Pledge.cs
Adds the ability to pass a standard id to the application-details route so we can just return the one standard
=> [TM-36] - Extend LTM Application-Details route

src/SFA.DAS.ApprenticeCommitments/Application/Services/ApprenticeLogin/ApprenticeLoginClient.cs, src/SFA.DAS.Campaign/ExternalApi/ContentfulApiClient.cs, src/SFA.DAS.SharedOuterApi/Infrastructure/ApiClient.cs, src/SFA.DAS.SharedOuterApi/Infrastructure/CustomerEngagementApiClient.cs, src/SFA.DAS.SharedOuterApi/Infrastructure/GetApiClient.cs, src/SFA.DAS.SharedOuterApi/Infrastructure/HttpRequestMessageExtensions.cs, src/SFA.DAS.SharedOuterApi/Infrastructure/InternalApiClient.cs
Change so that the default request header is no longer used for the version or authorization due to the default headers not being thread safe. The version and auth are now added to the request instead
=> TM-151 - Issue with DefaultRequestHeader

src/SFA.DAS.LevyTransferMatching.Api.UnitTests/Controllers/ApplicationTests/WhenCallingDeclined.cs, src/SFA.DAS.LevyTransferMatching.Api/Controllers/ApplicationsController.cs, src/SFA.DAS.LevyTransferMatching.Api/Models/Applications/GetDeclinedResponse.cs, src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/Applications/GetDeclined/WhenCallingHandle.cs, src/SFA.DAS.LevyTransferMatching/Application/Queries/Applications/GetDeclined/GetDeclinedQuery.cs, src/SFA.DAS.LevyTransferMatching/Application/Queries/Applications/GetDeclined/GetDeclinedQueryHandler.cs, src/SFA.DAS.LevyTransferMatching/Application/Queries/Applications/GetDeclined/GetDeclinedResult.cs
APIM changes required for the confirmation page when declining accepted funds.
Note: targets `TM-54-Decline-Funding-For-Approved-Applications`.
See also:
* https://github.com/SkillsFundingAgency/das-levy-transfer-matching-web/pull/110
=> [TM-132] Confirmation Page for Declined Funds (Receiver)

src/SFA.DAS.Vacancies.Manage.Api.UnitTests/Models/WhenMappingCreateVacancyRequestToMediatorCommand.cs, src/SFA.DAS.Vacancies.Manage.Api/Models/CreateVacancyRequest.cs
Fix an issue where the fixed waged was not being correctly set to null for cases where the wage type was not fixed. This was then causing issues in FAA when indexing the data.
=> FAI-236 - Set FixedWageYearAmount to null if not Fixed wage

src/SFA.DAS.Vacancies.Manage.Api.UnitTests/Controllers/WhenCreatingVacancy.cs, src/SFA.DAS.Vacancies.Manage.Api/Controllers/VacancyController.cs, src/SFA.DAS.Vacancies.Manage.Api/Models/CreateVacancyRequest.cs
Add mapping for standards lars code and the alternative employer name if there is a validation error from the inner api
=> FAI-221 - Add mapping for fields from HttpRequestContentException

src/ApprenticeAan/SFA.DAS.ApprenticeAan.Api.UnitTests/Controllers/NotificationsControllerTests.cs, src/ApprenticeAan/SFA.DAS.ApprenticeAan.Api/Controllers/NotificationsController.cs, src/ApprenticeAan/SFA.DAS.ApprenticeAan.Application/Infrastructure/IAanHubRestApiClient.cs, src/ApprenticeAan/SFA.DAS.ApprenticeAan.Application/InnerApi/Notifications/GetNotificationResponse.cs
Add endpoint to get notification by Id to pass through to inner API endpoint.
=> CSP-989 Add get notification endpoint to apprentice API

src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Models/GetLiveVacanciesApiResponse.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingGetLiveVacancies.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/GetLiveVacanciesQueryHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/GetLiveVacanciesQueryResult.cs
This PR includes:
- removing any traineeships from the `GetVacancies` API response
- Adding the `NumberOfPositions` property to the API response
=> FAI-970 Remove traineeships from API response

deployments/shared-infrastructure.yml, pipeline-templates/job/shared-arm-deploy.yml
**Context**
The current `shared-infrastructure.yml` failed to deploy and needed fixing. Subnet and ASP deployments were removed from the main shared infrastructure templates in 2021, but it doesn't look like the dedicated pipeline had been run since to check.
**Proposed changes**
- Update references to external repositories
- Remove reference to removed pipelines
- Ensure the code is checked out as it's not pulled from a different pipeline
=> DASD-11129 - Fix Shared APIM Infrastructure Deployment Pipeline

Directory.Packages.props
Updated NUnit generates warning as there is package dependency on <= 4.0.0
=> Fixed duplicate package reference and dropped Nunit to 4.0.0

src/ProviderPR/SFA.DAS.ProviderPR.UnitTests/Application/Queries/GetRelationships/GetRelationshipsQueryHandlerTests.cs, src/ProviderPR/SFA.DAS.ProviderPR.UnitTests/InnerApi/Requests/GetProviderRelationshipsRequestTests.cs, src/ProviderPR/SFA.DAS.ProviderPR/Application/Relationships/Queries/GetRelationships/GetRelationshipsQueryHandler.cs, src/ProviderPR/SFA.DAS.ProviderPR/Infrastructure/IProviderRelationshipsApiRestClient.cs, src/ProviderPR/SFA.DAS.ProviderPR/InnerApi/Requests/GetProviderRelationshipsRequest.cs, src/Shared/SFA.DAS.SharedOuterApi.Provider.DfeSignIn.Auth/Controllers/ProviderAccountsController.cs
- Updated provider relationships endpoint to use dictionary of filter values when passing filter values to the inner API.
=> CSP-1820: (Provider View employers and manage permissions) Filters/Search not working as expected

src/ApimDeveloper/SFA.DAS.ApimDeveloper.Api/Startup.cs, src/Apprenticeships/SFA.DAS.Apprenticeships.Api/Startup.cs, src/EmployerDemand/SFA.DAS.EmployerDemand.Api/Startup.cs, src/EmployerRequestApprenticeTraining/SFA.DAS.EmployerRequestApprenticeTraining.Api/Startup.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Startup.cs, src/LevyTransferMatching/SFA.DAS.LevyTransferMatching.Api/Startup.cs, src/ProviderRequestApprenticeTraining/SFA.DAS.ProviderRequestApprenticeTraining.Api/Startup.cs, src/Recruit/SFA.DAS.Recruit.Api/Program.cs
Bug:
'UpdateableServiceProvider' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'UpdateableServiceProvider' could be found (are you missing a using directive or an assembly reference?)
Solution:
Added GetAwaiter() for StartNServiceBus container Registration
=> Hot Fix: Added GetAwaiter() for StartNServiceBus container Registration

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Commands/Apply/WhenHandlingSubmitApplicationCommand.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Commands/Apply/WhenHandlingWithdrawApplicationCommand.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Commands/WhenHandlingDeleteCandidateCommand.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/WhenHandlingWithdrawApplicationQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Services/VacancyService/WhenGettingAClosedVacancy.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Services/VacancyService/WhenGettingAVacancy.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Apply/SubmitApplication/SubmitApplicationCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Apply/WithdrawApplication/WithdrawApplicationCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Users/DeleteCandidate/DeleteCandidateCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/WithdrawApplication/WithdrawApplicationQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Services/IVacancyService.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Services/VacancyService.cs
Bug: https://skillsfundingagency.atlassian.net/browse/FAI-2238
1. In case of closed vacancy, the response object could not be cast into GetApprenticeshipVacancyItemResponse
This results in a vacancy item response as NULL. If the email tokens are empty, then the email will not be sent.
2.  Vacancy service => Separation of Concerns rule violation split this implementation as separate methods GetVacancy from FAA Api & Closed Vacancy from RAA Api
=> FAI-2238 Withdraw Application Email failing to send if the Vacancy is Closed

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Apply/WhenHandlingGetIndexQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Apply/Index/GetIndexQueryHandler.cs
When answers are imported from a previous application the vacancy it was for is looked up to populate some details. When this can not be retrieved it is causing a 500 error to be returned
=> FAI-2284 - Fix issue with previous vacancy not found on application

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Applications/WhenHandlingGetIndexQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Applications/GetApplications/GetApplicationsQueryHandler.cs
- Introduced a new test in `WhenHandlingGetIndexQuery.cs` to verify that an empty API response results in zero applications.
- Removed unnecessary import statement and initialized `applicationApiResponse.Applications` as an empty array.
- Updated the condition in `GetApplicationsQueryHandler.cs` to return an empty result if either the total application count or the application list is empty.
=> FAI-2264 Added logic to check the Application count before calling Inner Api

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/GetSavedVacancies/GetSavedVacanciesQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/Responses/GetVacanciesByReferenceApiResponse.cs
Updated the `OtherAddresses` property in `GetSavedVacanciesQuery` to be nullable, allowing for more flexible handling. Modified the vacancy retrieval method to safely handle null values for `OtherAddresses`.
Additionally, enhanced the `GetVacanciesByReferenceApiResponse` class to return null for `OtherAddresses` when the `EmployerLocationOption` is not set to `AvailableWhere.MultipleLocations`.
=> FAI-2232 Refactor OtherAddresses to support null values

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Apply/WhenHandlingGetIndexQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Vacancies/ApplyCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Applications/GetApplication/GetApplicationViewQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Apply/GetApplication/GetApplicationQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Apply/Index/GetIndexQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/CandidateApi/Requests/PutApplicationApiRequest.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/CandidateApi/Responses/GetApplicationApiResponse.cs
Story: https://skillsfundingagency.atlassian.net/browse/FAI-2326
✨ Refactor handling of additional questions in the application process
- Update `WhenHandlingGetIndexQuery.cs` to sort additional questions by order.
- Change `additionalQuestions` in `ApplyCommandHandler.cs` to use key-value pairs.
- Ensure additional questions are ordered in `GetApplicationViewQueryHandler.cs`.
- Modify `PutApplicationApiRequest` to use a list of key-value pairs for questions.
- Add `QuestionOrder` property to `Question` class in `GetApplicationApiResponse.cs`.
=> FAI-2326 Preserve additional questions ordering

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/RecruitApi/Responses/GetClosedVacancyResponse.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Responses/GetLiveVacanciesApiResponse.cs
✨ Refactor vacancy response classes for improved serialization
- Enhanced `GetClosedVacancyResponse.Address` getter logic.
- Simplified `OtherAddresses` property in `GetClosedVacancyResponse`.
- Updated `EmployerLocationOption` with JSON converter in both classes.
- Added `System.Text.Json.Serialization` using directive in `GetLiveVacanciesApiResponse`.
- Initialized `EmployerLocations` to an empty list in `GetLiveVacanciesApiResponse`.
=> FAI-2275 Enable FAA user accounts to display single location vacancies when deleting account

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/RecruitApi/Responses/GetClosedVacancyResponse.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Responses/GetLiveVacanciesApiResponse.cs
✨ Update vacancy response classes with new location options
- Added `EmployerLocationOption` to `GetClosedVacancyResponse`.
- Removed old `employerLocationOption` property from the same class.
- Included `System.Text.Json.Serialization` namespace in `GetLiveVacanciesApiResponse`.
- Introduced `EmployerLocationOption` in `LiveVacancy` class.
- Both new properties use JSON converters for `AvailableWhere` enum.
=> FAI-2275 BUG AvailableWhere Json Serialization Error

src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingProcessApplicationReminder.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingProcessVacancyClosedEarlyCommand.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Domain/EmailTemplates/EmailTemplateBuilderTests.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/ProcessApplicationReminderCommandHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/ProcessVacancyClosedEarlyCommandHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Domain/Constants/EmailTemplateBuilderConstants.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Domain/EmailTemplates/EmailTemplateBuilder.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.csproj
✨ Refactor employer location handling in email templates
- Updated `WhenHandlingProcessApplicationReminder` and `WhenHandlingProcessVacancyClosedEarlyCommand` to use a list of employer locations.
- Modified tests in `EmailTemplateBuilderTests` to reflect new employer location structure.
- Enhanced `ProcessApplicationReminderCommandHandler` and `ProcessVacancyClosedEarlyCommandHandler` to support multiple location options.
- Introduced `EmailTemplateBuilderConstants` for centralized string management.
- Cleaned up `EmailTemplateBuilder` and updated project file for .NET SDK compatibility.
=> FAI-2265 FAI-2271 Bug Amendments to Email Template Builder for One Location

src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Models/SavedSearchApiRequest.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingProcessApplicationReminder.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingProcessVacancyClosedEarlyCommand.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Domain/EmailTemplates/EmailTemplateBuilderTests.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.sln, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/ProcessApplicationReminderCommandHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/ProcessVacancyClosedEarlyCommandHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/SavedSearch/SendNotification/PostSendSavedSearchNotificationCommand.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/SavedSearch/SendNotification/PostSendSavedSearchNotificationCommandHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Domain/EmailTemplates/EmailTemplateBuilder.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Responses/GetLiveVacanciesApiResponse.cs, src/Shared/SFA.DAS.SharedOuterApi.UnitTests/Extensions/EmailTemplateAddressExtensionTests.cs, src/Shared/SFA.DAS.SharedOuterApi/Extensions/EmailTemplateAddressExtension.cs
✨ Refactor address handling in API and tests
- Replaced `EmployerLocations` with `OtherAddresses` in `SavedSearchApiRequest.cs`.
- Updated tests in `WhenHandlingProcessApplicationReminder.cs` to use constants.
- Modified `WhenHandlingProcessVacancyClosedEarlyCommand.cs` for address consistency.
- Adjusted `EmailTemplateBuilder.cs` to reflect new property names.
- Added unit tests in `EmailTemplateAddressExtensionTests.cs` for address methods.
=> FAI-2265 FAI-2271 Bug fixes related to Email Notifications Issues

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Commands/Vacancies/WhenHandlingDeleteSavedVacancyCommand.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Applications/WhenHandlingGetAccountDeletionQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Applications/WhenHandlingGetIndexQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/SearchByVacancyReference/WhenHandlingGetApprenticeshipVacancyQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/SearchByVacancyReference/WhenMappingFromGetClosedVacancyResponseToVacancy.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Vacancies/WhenHandlingApplyCommand.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Apply/WithdrawApplication/WithdrawApplicationCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Users/DeleteCandidate/DeleteCandidateCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Vacancies/ApplyCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Vacancies/DeleteSavedVacancy/DeleteSavedVacancyCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Vacancies/SaveVacancy/SaveVacancyCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Applications/GetApplications/GetApplicationsQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/GetSavedVacancies/GetSavedVacanciesQuery.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchApprenticeships/SearchApprenticeshipsQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchByVacancyReference/GetApprenticeshipVacancyQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchByVacancyReference/GetApprenticeshipVacancyQueryResult.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Users/GetAccountDeletionQuery/GetAccountDeletionQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Services/VacancyService.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Telemetry/FindAnApprenticeshipMetrics.cs, src/Shared/SFA.DAS.SharedOuterApi.UnitTests/Extensions/StringExtensionsTests.cs, src/Shared/SFA.DAS.SharedOuterApi/Extensions/StringExtensions.cs, src/Vacancies/SFA.DAS.Vacancies.Api.UnitTests/Controllers/WhenGettingVacancy.cs, src/Vacancies/SFA.DAS.Vacancies.Api/Controllers/VacancyController.cs, src/Vacancies/SFA.DAS.Vacancies/Application/Vacancies/Queries/GetVacanciesQueryHandler.cs
✨ Refactor vacancy reference handling with new extension
- Introduced `TrimVacancyReference` method in `StringExtensions`.
- Replaced `Replace("VAC", "", ...)` with `TrimVacancyReference()` calls.
- Updated command and query handlers for consistent vacancy reference handling.
- Added `StringExtensionsTests` to verify the new method's functionality.
- Included `using SFA.DAS.SharedOuterApi.Extensions;` in relevant files.
=> FAI-2370 Bug : Exception due to the new ML vacancy references

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Controllers/SearchApprenticeshipsController.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/SavedSearches/PostSaveSearchApiRequest.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/InnerApi/FindApprenticeApi/Responses/Shared/WhenComparingSearchParametersDto.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/SaveSearch/CreateSaveSearch/SaveSearchCommand.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/SaveSearch/CreateSaveSearch/SaveSearchCommandHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SavedSearches/GetUnsubscribeSavedSearchQueryResult.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchApprenticeships/SearchApprenticeshipsQueryHandler.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Users/GetSavedSearch/GetCandidateSavedSearchQueryResult.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Domain/Models/SearchParameters.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/FindApprenticeApi/Responses/Shared/SavedSearchDto.cs, src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/FindApprenticeApi/Responses/Shared/SearchParametersDto.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Controllers/SavedSearchesController.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Models/GetCandidateSavedVacanciesRequest.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Models/SavedSearchApiRequest.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Domain/EmailTemplates/EmailTemplateBuilderTests.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/InnerApi/WhenBuildingGetVacanciesRequest.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/SavedSearches/WhenHandlingGetSavedSearchVacanciesQuery.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/SavedSearch/SendNotification/PostSendSavedSearchNotificationCommand.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/SavedSearch/SendNotification/PostSendSavedSearchNotificationCommandHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearchVacancies/GetSavedSearchVacanciesQuery.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearchVacancies/GetSavedSearchVacanciesQueryHandler.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearchVacancies/GetSavedSearchVacanciesQueryResult.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearches/GetSavedSearchesQueryResult.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Domain/EmailTemplates/EmailTemplateBuilder.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Requests/GetVacanciesRequest.cs, src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Responses/GetSavedSearchesApiResponse.cs
✨ Add ExcludeNational property to search parameters
- Introduced optional boolean `ExcludeNational` to several classes.
- Updated `PostSaveSearchApiRequest` and `SaveSearchCommand` to include it.
- Modified `SearchParameters` and `SearchParametersDto` to support the new property.
- Adjusted test cases to ensure proper comparisons with `ExcludeNational`.
- Enhanced search functionality for users to exclude national options.
=> FAI-2331 Add Nationwide Filter Search Alert

src/Recruit/SFA.DAS.Recruit.UnitTests/Application/Candidates/Commands/WhenHandlingCandidateApplicationStatusCommand.cs, src/Recruit/SFA.DAS.Recruit/Application/Candidates/Commands/CandidateApplicationStatus/CandidateApplicationStatusCommandHandler.cs
✨ Update location handling in application status commands
- Rename test methods to handle null/empty location values.
- Align tests with new logic that defaults to "Unknown" location.
- Modify `GetLocation` method to accept a string parameter.
- Simplify location logic to ensure meaningful email tokens.
- Improve code clarity and maintainability by separating concerns.
=> FAI-2431 Missing location on unsuccessful application email

src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Controllers/Courses/WhenCallingGetCourseByLarsCode.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Controllers/Shortlist/WhenCallingPostToCreateShortlistUserItem.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Services/WhenCallingCachedLocationLookupService.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api/ApiRequests/CreateShortListRequest.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api/AppStart/AddServiceRegistrationExtension.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/CoursesController.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/ShortlistsController.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.Api/Properties/launchSettings.json, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/Courses/Queries/GetCourseByLarsCode/WhenGettingCourseByLarsCode.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/Courses/Queries/GetCourseProviders/WhenGettingProvidersByTrainingCourse.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/Shortlist/Commands/WhenCreatingShortlistForUser.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Application/Courses/Queries/GetCourseByLarsCode/GetCourseByLarsCodeQuery.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Application/Courses/Queries/GetCourseByLarsCode/GetCourseByLarsCodeQueryHandler.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Application/Courses/Queries/GetCourseProviders/GetTrainingCourseProvidersQueryHandler.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Application/Courses/Queries/GetCourses/GetCoursesQueryHandler.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Application/Shortlist/Commands/CreateShortlistForUser/CreateShortlistForUserCommand.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Application/Shortlist/Commands/CreateShortlistForUser/CreateShortlistForUserCommandHandler.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/PostShortlistForUserRequest.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Services/CachedLocationLookupService.cs, src/Shared/SFA.DAS.SharedOuterApi.UnitTests/Models/WhenCreatingLocationItemModelTests.cs, src/Shared/SFA.DAS.SharedOuterApi.UnitTests/Services/LocationLookupServiceTests/WhenCallingGetExactMatchAddresses.cs, src/Shared/SFA.DAS.SharedOuterApi.UnitTests/Services/LocationLookupServiceTests/WhenCallingGetLocationInformation.cs, src/Shared/SFA.DAS.SharedOuterApi/Models/LocationItem.cs, src/Shared/SFA.DAS.SharedOuterApi/Services/LocationLookupService.cs
- Cache **LocationItem** response when getting **LocationInformation** from the Location API.
- Contains updates to **CoursesController** - **GetCourseByLarsCode** method removing **Lat** & **Lon** in place of Location for **CSP-1675**: Apprenticeship Training Course Details.
=> CSP-1924: FAT Outer API: Cache Location API Response

src/Aodp/SFA.DAS.Aodp.Api.UnitTests/Controllers/Qualification/QualificationControllerTests.cs, src/Aodp/SFA.DAS.Aodp.Api/Controllers/Qualification/QualificationsController.cs, src/Aodp/SFA.DAS.Aodp.UnitTests/Application/Commands/Application/Qualifications/CreateQualificationDiscussionHistoryCommandHandlerTests.cs, src/Aodp/SFA.DAS.Aodp/Application/Commands/Application/Qualifications/CreateQualificationDiscussionHistoryCommand.cs, src/Aodp/SFA.DAS.Aodp/Application/Commands/Application/Qualifications/CreateQualificationDiscussionHistoryCommandHandler.cs, src/Aodp/SFA.DAS.Aodp/InnerApi/AodpApi/Qualifications/CreateQualificationDiscussionHistoryApiRequest.cs
Renamed the Api endpoints to 'funding-offers-history-note' Renamed the command name to 'CreateQualificationDiscussionHistoryNoteForFundingOffers'
=> Create Qualification Discussion History changes

src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingGetCourseProviderDetailsRequest.cs, src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/GetCourseProviderDetailsRequest.cs
- Removed location encoding to allow for the rematching of location to the related shortlist item.
=> CSP-1692: Fixed double encoding in training provider details endpoint request

src/AdminAan/azure-pipelines.yml, src/AparRegister/azure-pipelines.yml, src/EmployerAan/azure-pipelines.yml, src/EmployerPR/azure-pipelines.yml, src/FindApprenticeshipTraining/azure-pipelines.yml, src/ProviderPR/azure-pipelines.yml, src/Roatp/azure-pipelines.yml, src/RoatpCourseManagement/azure-pipelines.yml, src/RoatpOversight/azure-pipelines.yml, src/RoatpProviderModeration/azure-pipelines.yml
CSP-2063 - Upgraded the following outers to use das-platform-building-blocks to tag number 3.0.8:
AdminAan
AparRegister
EmployerAan
EmployerPR
FindApprenticeshipTraining
ProviderPR
Roatp
RoatpCourseManagement
RoatpOversight
RoatpProviderModeration
=> CSP-2063 - Upgraded das-platform-building-blocks to tag number 3.0.8

src/Vacancies/SFA.DAS.Vacancies.Api.UnitTests/Models/WhenMappingFromMediatorResponseToGetVacancyResponseV2.cs, src/Vacancies/SFA.DAS.Vacancies.Api/Models/GetVacanciesListResponseV2.cs, src/Vacancies/SFA.DAS.Vacancies.Api/Models/GetVacancyResponseV2.cs
✨ Update vacancy response models and mappings
- Excluded `Address` and `OtherAddresses` in mapping logic.
- Added null handling test for `Vacancy` in response mapping.
- Enhanced `GetVacanciesListResponseItemV2` with new properties and validation.
- Improved parsing for `VacancyReference` and `Ukprn` for safety.
- Simplified address handling and national vacancy logic in responses.
=> FAI-2553 Improvements to the V2 Response

azure/template.json
This PR does 2 things:
1) Point the Your Apprentice App alerts to the main slack channel
2) Due to the nature of this repositroy/variable structure, it's hard to manage the rollout of these alerts granually, this change ensures that FAA and EA Outer API response alerting gets sent to the test channel.
=> modified products sending alerts to das-alerts-test

src/AdminRoatp/SFA.DAS.AdminRoatp.Api.UnitTests/Controllers/OrganisationsControllerTests/OrganisationsControllerGetOrganisationTests.cs, src/AdminRoatp/SFA.DAS.AdminRoatp.Api.UnitTests/Controllers/OrganisationsControllerTests/OrganisationsControllerGetOrganisationsTests.cs, src/AdminRoatp/SFA.DAS.AdminRoatp.Api/Controllers/OrganisationsController.cs, src/AdminRoatp/SFA.DAS.AdminRoatp.UnitTests/Application/Queries/GetOrganisation/GetOrganisationQueryHandlerTests.cs, src/AdminRoatp/SFA.DAS.AdminRoatp.UnitTests/Application/Queries/GetOrganisation/GetOrganisationQueryTests.cs, src/AdminRoatp/SFA.DAS.AdminRoatp/Application/Queries/GetOrganisation/GetOrganisationQuery.cs, src/AdminRoatp/SFA.DAS.AdminRoatp/Application/Queries/GetOrganisation/GetOrganisationQueryHandler.cs, src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Requests/Roatp/GetOrganisationRequest.cs, src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/Roatp/AllowedCourseType.cs, src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/Roatp/Common/LearningType.cs, src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/Roatp/Common/OrganisationStatus.cs, src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/Roatp/Common/ProviderType.cs, src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/Roatp/GetOrganisationResponse.cs
CSP-2229 Implements search organisation endpoint
CSP-2229 Separated search organisation response class to different class files
CSP-2229 Removed unnecessary code block and added loging
CSP-2229 Added code to handle not found response
CSP-2229 Added swagger doc ref for not found
CSP-2229 Amended code to resolve review comments
CSP-2229 Reverted changes to controller name and route
CSP-2229 Amendments made to address further review comments
CSP-2229 Amended route to fix build error
=> CSP-2229 Implements search organisation endpoint
