src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Controllers/TrainingCourses/WhenCallingGetTrainingCoursesList.cs
src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingGetTrainingCourseResponseToLevels.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/TrainingCoursesController.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCoursesListResponse.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingLevelsListItem.cs
src/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/TrainingCourses/Queries/WhenGettingTrainingCourseList.cs
src/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingTheGetLevelsListRequest.cs
src/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingTheGetStandardsListRequest.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCoursesList/GetTrainingCoursesListQuery.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCoursesList/GetTrainingCoursesListQueryHandler.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCoursesList/GetTrainingCoursesListResult.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/GetLevelsListRequest.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/GetStandardsListRequest.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetLevelsListItem.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetLevelsListResponse.cs

Add levels to GetTraining response, also added ability to filter by levels

FAT2-93 levels

---

src/SFA.DAS.Reservations.Api/Startup.cs

Update Reservations Outer Api Title

Fat2 133 reservations

---

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Controllers/TrainingCourses/WhenCallingGetTrainingCourseProvidersList.cs
src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingGetTrainingCourseProvidersResponseFromMediatorType.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/TrainingCoursesController.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseListItem.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseProviderListItem.cs
src/SFA.DAS.FindApprenticeshipTraining.UnitTests/InnerApi/Requests/WhenBuildingTheGetProvidersByCourseRequest.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Requests/GetProvidersByCourseRequest.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetProvidersListItem.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetStandardsListItem.cs

Requires changes from course and course delivery api for running

FAT2-77 achievement rates

---

src/SFA.DAS.EmployerIncentives.Api.AcceptanceTests/Steps/HealthCheckSteps.cs
src/SFA.DAS.EmployerIncentives.UnitTests/Application/Services/EmployerIncentivesServiceTests/WhenCallingHealthCheck.cs
src/SFA.DAS.EmployerIncentives/InnerApi/Requests/GetHealthRequest.cs

Edited employer incentives inner api health request to ping path
Employer incentives api health path change in https://github.com/SkillsFundingAgency/das-employer-incentives/pull/75

Edited employer incentives inner api health request to ping path

---

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingGetTrainingCourseResponseFromMediatorType.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseListItem.cs

creating a new branch for the PR as I merged sprint_release into the previous one by mistake. previous PR #99

FAT2-108 new start date

---

src/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/TrainingCoursesController.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseProvidersResponse.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCourseProviders/GetTrainingCourseProvidersQueryHandler.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCourseProviders/GetTrainingCourseProvidersResult.cs
src/SFA.DAS.SharedOuterApi.UnitTests/Infrastructure/Api/WhenCallingGet.cs

* Return default if not found from get request

FAT2-166 - Add location property to providers response

---

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Models/WhenCastingToProviderBaseTypesFromMediatorType.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/ProviderCourseBase.cs

Correct upper boundary of excellent

FAT-205 sprint release

---

src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetDeliveryType.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/ProviderCourseBase.cs
src/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/TrainingCourses/Queries/WhenGettingProviderByTrainingCourse.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCourseProvider/GetTrainingCourseProviderQueryHandler.cs

Latetst APIM for Sprint Release

FAT2-204 - Sprint Release

---

src/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/TrainingCoursesController.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseListItem.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseResponse.cs
src/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/TrainingCourses/Queries/WhenGettingTrainingCourse.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCourse/GetTrainingCourseQueryHandler.cs
src/SFA.DAS.FindApprenticeshipTraining/InnerApi/Responses/GetStandardsListItem.cs

Add an 'Equivalent Level...' under the Standard Level on Course Details

FAT2-245_add_level_label

---

src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Extensions/WhenOrderingByProviderRating.cs
src/SFA.DAS.FindApprenticeshipTraining.Api.UnitTests/Extensions/WhenOrderingByProviderScoreAndDistance.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Controllers/TrainingCoursesController.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Extensions/TrainingCourseProviderGroupByDistanceAndScoreExtension.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Extensions/TrainingCourseProviderOrderByExtension.cs
src/SFA.DAS.FindApprenticeshipTraining.Api/Models/GetTrainingCourseResponse.cs

Make sure that At Work Place only are grouped together with similar scores and not put into one group on their own.
Split out extension to do scoring, then grouping on distance by score. Created separate test file.

FAT2-333 - Change to provider ordering

---

src/SFA.DAS.Apim.Endpoints.sln
src/SFA.DAS.ApprenticeCommitments.Api/AppStart/AddServiceRegistrationExtension.cs
src/SFA.DAS.ApprenticeCommitments.Api/Controllers/ApprenticeshipController.cs
src/SFA.DAS.ApprenticeCommitments.Api/ErrorHandler/ErrorHandlerExtensions.cs
src/SFA.DAS.ApprenticeCommitments.Api/Program.cs
src/SFA.DAS.ApprenticeCommitments.Api/Properties/launchSettings.json
src/SFA.DAS.ApprenticeCommitments.Api/SFA.DAS.ApprenticeCommitments.Api.csproj
src/SFA.DAS.ApprenticeCommitments.Api/Startup.cs
src/SFA.DAS.ApprenticeCommitments.Api/appsettings.json
src/SFA.DAS.ApprenticeCommitments.Api/nlog.Debug.config
src/SFA.DAS.ApprenticeCommitments.Api/nlog.Release.config
src/SFA.DAS.ApprenticeCommitments.Api/nlog.config
src/SFA.DAS.ApprenticeCommitments/Application/Commands/CreateApprenticeship/CreateApprenticeshipCommand.cs
src/SFA.DAS.ApprenticeCommitments/Application/Commands/CreateApprenticeship/CreateApprenticeshipCommandHandler.cs
src/SFA.DAS.ApprenticeCommitments/Application/Services/ApprenticeCommitmentsService.cs
src/SFA.DAS.ApprenticeCommitments/Configuration/ApprenticeCommitmentsConfiguration.cs
src/SFA.DAS.ApprenticeCommitments/Configuration/AzureManagedIdentityApiConfiguration.cs
src/SFA.DAS.ApprenticeCommitments/Infrastructure/ApprenticeCommitmentsHealthCheck.cs
src/SFA.DAS.ApprenticeCommitments/InnerApi/Requests/CreateApprenticeshipRequest.cs
src/SFA.DAS.ApprenticeCommitments/InnerApi/Requests/GetHealthRequest.cs
src/SFA.DAS.ApprenticeCommitments/SFA.DAS.ApprenticeCommitments.csproj
src/SFA.DAS.EmployerIncentives.Api/SFA.DAS.EmployerIncentives.Api.csproj

Project structure for the Apprentice Commitment API.
https://skillsfundingagency.atlassian.net/wiki/spaces/NDL/pages/2440101994/eCommitments+-+C4+Component+ViewPoint

🎉 ApprenticeCommitment Outer API

---

src/SFA.DAS.FindEpao.UnitTests/InnerApi/Requests/Responses/WhenBuildingTheOrganisationWebsite.cs
src/SFA.DAS.FindEpao/InnerApi/Responses/GetEpaoResponse.cs

Correct issue that if the url is blank or null then nothing is done to it

FAT2-385 - EPAO url

---

src/SFA.DAS.FindApprenticeshipTraining.UnitTests/Application/TrainingCourses/Queries/WhenGettingProviderByTrainingCourse.cs
src/SFA.DAS.FindApprenticeshipTraining/Application/TrainingCourses/Queries/GetTrainingCourseProvider/GetTrainingCourseProviderQueryHandler.cs

Always return all courses the provider also offers

FAT2-445 - Include all courses in additional courses

---

src/SFA.DAS.EmployerDemand.Api.UnitTests/Controllers/Demand/WhenCreatingCourseDemand.cs
src/SFA.DAS.EmployerDemand.Api/ApiRequests/CreateCourseDemandRequest.cs
src/SFA.DAS.EmployerDemand.Api/Controllers/DemandController.cs
src/SFA.DAS.EmployerDemand.Api/Program.cs
src/SFA.DAS.EmployerDemand.UnitTests/Application/Demand/Commands/WhenHandlingRegisterDemandCommand.cs
src/SFA.DAS.EmployerDemand/Application/Demand/Commands/RegisterDemand/RegisterDemandCommand.cs
src/SFA.DAS.EmployerDemand/Application/Demand/Commands/RegisterDemand/RegisterDemandCommandHandler.cs
src/SFA.DAS.EmployerDemand/InnerApi/Requests/PostCreateCourseDemandRequest.cs

Pass entry point from create demand to inner api

AEDB-96 demand entry point

---

src/SFA.DAS.Assessors.Api/Models/GetStandardDetailsResponse.cs
src/SFA.DAS.Assessors/InnerApi/Responses/StandardDetailResponse.cs

SV-350-StandardVersioningApply

---

src/SFA.DAS.ApprenticeCommitments.MockApis/Program.cs
src/SFA.DAS.ApprenticeCommitments/Application/Commands/CreateApprenticeship/CreateApprenticeshipCommandHandler.cs
src/SFA.DAS.ApprenticeCommitments/Application/Commands/CreateApprenticeship/CreateApprenticeshipResponse.cs

This should be merged after CS-288 has been merged.

Cs 777 move invitation configs from apim to jobs

---

azure-pipelines-build.yml
pipeline-templates/job/code-build.yml

- Changed agent pool to DAS - Continuous Integration Agents: Resolves intermittent build failures as build agent will now be Ubuntu 20
- Updated GitVersion tasks to latest version

code-build.yml: Changed agent pool to DAS - Continuous Integration Agents

---

src/SFA.DAS.LevyTransferMatching.Api.UnitTests/Authorisation/PledgeAuthorizationHandlerTests.cs
src/SFA.DAS.LevyTransferMatching.Api.UnitTests/Controllers/PledgeTests/GetPledgeApplications.cs
src/SFA.DAS.LevyTransferMatching.Api.UnitTests/Controllers/PledgeTests/GetPledgeApplicationsTests.cs
src/SFA.DAS.LevyTransferMatching.Api/Authentication/PledgeAuthorizationHandler.cs
src/SFA.DAS.LevyTransferMatching.Api/Authentication/PledgeRequirement.cs
src/SFA.DAS.LevyTransferMatching.Api/Authentication/PolicyNames.cs
src/SFA.DAS.LevyTransferMatching.Api/Authorization/RouteValueKeys.cs
src/SFA.DAS.LevyTransferMatching.Api/Controllers/PledgeController.cs
src/SFA.DAS.LevyTransferMatching.Api/Models/Pledges/GetApplicationsResponse.cs
src/SFA.DAS.LevyTransferMatching.Api/Startup.cs
src/SFA.DAS.LevyTransferMatching.UnitTests/Application/Queries/Pledges/GetApplications/GetApplicationsQueryHandlerTests.cs
src/SFA.DAS.LevyTransferMatching/Application/Queries/Pledges/GetApplications/GetApplicationsQuery.cs
src/SFA.DAS.LevyTransferMatching/Application/Queries/Pledges/GetApplications/GetApplicationsQueryHandler.cs
src/SFA.DAS.LevyTransferMatching/Application/Queries/Pledges/GetApplications/GetApplicationsQueryResult.cs
src/SFA.DAS.LevyTransferMatching/Application/Services/LevyTransferMatchingService.cs
src/SFA.DAS.LevyTransferMatching/InnerApi/LevyTransferMatching/Requests/GetApplicationsRequest.cs
src/SFA.DAS.LevyTransferMatching/InnerApi/LevyTransferMatching/Requests/GetApplicationsResponse.cs
src/SFA.DAS.LevyTransferMatching/Interfaces/ILevyTransferMatchingService.cs
src/SFA.DAS.LevyTransferMatching/Models/Application.cs
src/SFA.DAS.LevyTransferMatching/Models/ApprenticeshipFunding.cs
src/SFA.DAS.LevyTransferMatching/Models/Standard.cs
src/SFA.DAS.LevyTransferMatching/SFA.DAS.LevyTransferMatching.csproj

Requires TM-47 LTM Api and Web branches

[TM-47] - View list of applications

---

deployments/apim-developer.yml
deployments/apprentice-commitments.yml
deployments/approvals.yml
deployments/assessors.yml
deployments/campaign.yml
deployments/employer-contact-forms.yml
deployments/employer-demand.yml
deployments/employer-incentives.yml
deployments/epao-register.yml
deployments/find-an-apprenticeship.yml
deployments/find-apprenticeship-training.yml
deployments/find-epao.yml
deployments/forecasting.yml
deployments/levy-transfer-matching.yml
deployments/manage-apprenticeships.yml
deployments/recruit.yml
deployments/reservations.yml
deployments/shared-infrastructure.yml
deployments/vacancies.yml
deployments/vacanciesmanage.yml
pipeline-templates/job/arm-deploy.yml
pipeline-templates/job/shared-arm-deploy.yml

- Updated das-platform-building-blocks refs from 0.4.14 to 0.4.26
- Updated das-platform-automation refs from 4.5.7 to 4.5.9

shared-arm-deploy.yml, arm-deploy.yml: Add wait azure devops deployment step

---

deployments/vacancies.yml

Reverts SkillsFundingAgency/das-apim-endpoints#589

Revert "vacancies.yml: Enabled Sandbox APIs"

---

src/SFA.DAS.Vacancies.Api.UnitTests/Controllers/WhenGettingVacancies.cs
src/SFA.DAS.Vacancies.Api.UnitTests/Models/WhenMappingFromMediatorResponseToGetVacanciesListResponse.cs
src/SFA.DAS.Vacancies.Api/ApiRequests/SearchVacancyRequest.cs
src/SFA.DAS.Vacancies.Api/Controllers/VacancyController.cs
src/SFA.DAS.Vacancies.Api/Models/GetVacanciesListResponse.cs
src/SFA.DAS.Vacancies.UnitTests/Application/Vacancies/Queries/WhenHandlingGetVacancies.cs
src/SFA.DAS.Vacancies/Application/Vacancies/Queries/GetVacanciesQueryHandler.cs
src/SFA.DAS.Vacancies/Application/Vacancies/Queries/GetVacanciesQueryResult.cs
src/SFA.DAS.Vacancies/InnerApi/Responses/GetVacanciesResponse.cs

Totals now returned with vacancy search results. Also added in extra flag so that now your subscription will not automatically filter your results.

FAI-220 add totals to vacancy search

---

src/SFA.DAS.ApprenticePortal.Api/Controllers/ApprenticeHomepageController.cs

CS-1289-ApprenticePortalAPIM update endpoint

CS-1289-ApprenticePortalAPIM update endpoint

---

src/SFA.DAS.ApprenticeFeedback.Api.UnitTests/Controllers/WhenGettingProviderAttributes.cs
src/SFA.DAS.ApprenticeFeedback.Api/Controllers/ProviderAttributesController.cs
src/SFA.DAS.ApprenticeFeedback.UnitTests/Application/Apprentices/Queries/WhenHandlingGetProviderAttributesQuery.cs
src/SFA.DAS.ApprenticeFeedback/Application/Queries/GetProviderAttributes/GetProviderAttributesQuery.cs
src/SFA.DAS.ApprenticeFeedback/Application/Queries/GetProviderAttributes/GetProviderAttributesQueryHandler.cs
src/SFA.DAS.ApprenticeFeedback/Application/Queries/GetProviderAttributes/GetProviderAttributesResult.cs
src/SFA.DAS.ApprenticeFeedback/InnerApi/Requests/GetProviderAttributesRequest.cs
src/SFA.DAS.ApprenticeFeedback/InnerApi/Responses/GetProviderAttributesResponse.cs
src/SFA.DAS.ApprenticeFeedback/InnerApi/Responses/ProviderAttribute.cs

Outer API to surface provider attributes.

QF-294 get feedback attributes outer api

---

src/SFA.DAS.Vacancies.Api.UnitTests/Models/WhenMappingFromMediatorResponseToGetVacancyResponse.cs
src/SFA.DAS.Vacancies.Api/Models/GetVacancyResponse.cs

Removed duplicated wage description field from response for get vacancy detail

FAI-389 - Remove duplicate field

---

src/SFA.DAS.Roatp.CourseManagement.Api/AppStart/ServiceCollectionExtensions.cs
src/SFA.DAS.Roatp.CourseManagement.Api/Startup.cs
src/SFA.DAS.SharedOuterApi/Configuration/RoatpV2ApiConfiguration.cs
src/SFA.DAS.SharedOuterApi/Interfaces/IRoatpCourseManagementApiClient.cs
src/SFA.DAS.SharedOuterApi/Services/RoatpCourseManagementApiClient.cs

Roatp CourseManagement startup and config changes

Roatp CourseManagement startup and config changes

---

src/SFA.DAS.ManageApprenticeships.Api.UnitTests/Controllers/Transfers/WhenGettingFinancialBreakdown.cs
src/SFA.DAS.ManageApprenticeships.Api/Controllers/TransfersController.cs
src/SFA.DAS.ManageApprenticeships.Api/Models/Transfers/GetFinancialBreakdownResponse.cs
src/SFA.DAS.ManageApprenticeships.UnitTests/Application/Queries/Transfers/GetFinancialBreakdown/WhenHandlingTheGetFinancialBreakdownQuery.cs
src/SFA.DAS.ManageApprenticeships/Application/Queries/Transfers/GetFinancialBreakdown/GetFinancialBreakdownHandler.cs
src/SFA.DAS.ManageApprenticeships/Application/Queries/Transfers/GetFinancialBreakdown/GetFinancialBreakdownResult.cs
src/SFA.DAS.SharedOuterApi.UnitTests/InnerApi/Requests/WhenBuildingTheGetTransferFinancialBreakdownRequest.cs
src/SFA.DAS.SharedOuterApi/InnerApi/Requests/GetAccountTransferStatusRequest.cs
src/SFA.DAS.SharedOuterApi/InnerApi/Requests/GetTransferFinancialBreakdownRequest.cs
src/SFA.DAS.SharedOuterApi/InnerApi/Responses/GetTransferFinancialBreakdownResponse.cs

TM-44 future financial estimates APIM - View transfer finance details across financial years

TM-44 future financial estimates apim

---

src/SFA.DAS.ApprenticeFeedback/Application/Queries/GetApprenticeTrainingProvider/GetApprenticeTrainingProviderResult.cs
src/SFA.DAS.ApprenticeFeedback/Models/TrainingProvider.cs

GetTrainingProvider needs to pass back TimeWindow and SignificantDate incase the user games the URL in the UI

QF-272 multiple providers gaming fix

---

src/SFA.DAS.Roatp.CourseManagement.Api.UnitTests/Controllers/CourseDirectoryDataControllerTests.cs
src/SFA.DAS.Roatp.CourseManagement.Api/AppStart/ServiceCollectionExtensions.cs
src/SFA.DAS.Roatp.CourseManagement.Api/Configuration/CourseDirectoryConfiguration.cs
src/SFA.DAS.Roatp.CourseManagement.Api/Controllers/CourseDirectoryDataController.cs
src/SFA.DAS.Roatp.CourseManagement.Api/Startup.cs
src/SFA.DAS.Roatp.CourseManagement.UnitTests/Services/CourseDirectoryServiceTests.cs
src/SFA.DAS.Roatp.CourseManagement/Services/CourseDirectoryService.cs
src/SFA.DAS.Roatp.CourseManagement/Services/ICourseDirectoryService.cs

I have used a service in this case as I wanted a typed http client to associate with. Could have used a mediator handler on top of service, but it seemed pointless.

CSP-92 Implements endpoint to get course directory data

---

src/Approvals/SFA.DAS.Approvals.Api/Models/DraftApprenticeships/GetEditDraftApprenticeshipResponse.cs
src/Approvals/SFA.DAS.Approvals.UnitTests/Application/DraftApprenticeships/GetEditDraftApprenticeshipQueryHandlerTests.cs
src/Approvals/SFA.DAS.Approvals/Application/DraftApprenticeships/Queries/GetEditDraftApprenticeship/GetEditDraftApprenticeshipQueryHandler.cs
src/Approvals/SFA.DAS.Approvals/Application/DraftApprenticeships/Queries/GetEditDraftApprenticeship/GetEditDraftApprenticeshipQueryResult.cs
src/Approvals/SFA.DAS.Approvals/Application/OverlappingTrainingDateRequest/Command/ValidateDraftApprenticeshipRequest.cs
src/Approvals/SFA.DAS.Approvals/InnerApi/Responses/GetDraftApprenticeshipResponse.cs

Reverts SkillsFundingAgency/das-apim-endpoints#887

Revert "Flp 29 start date validation"

---

src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback.Api.UnitTests/Controllers/WhenPostingCreateExitSurvey.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback.Api/Controllers/ApprenticeFeedbackTargetController.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback.Api/Controllers/ExitSurveyController.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback.UnitTests/Application/Apprentices/Queries/WhenHandlingGetApprenticeFeedbackTargets.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback.sln
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Commands/CreateExitSurvey/CreateExitSurveyCommand.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Commands/CreateExitSurvey/CreateExitSurveyCommandHandler.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Commands/CreateExitSurvey/CreateExitSurveyResponse.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Queries/GetApprenticeFeedbackTargets/GetApprenticeFeedbackTargetsQuery.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Queries/GetApprenticeFeedbackTargets/GetApprenticeFeedbackTargetsQueryHandler.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Queries/GetApprenticeFeedbackTargets/GetApprenticeFeedbackTargetsResult.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Queries/GetExitSurvey/GetExitSurveyForApprenticeFeedbackTargetQuery.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Queries/GetExitSurvey/GetExitSurveyForApprenticeFeedbackTargetQueryHandler.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Application/Queries/GetExitSurvey/GetExitSurveyForApprenticeFeedbackTargetResult.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/InnerApi/Requests/CreateExitSurveyRequest.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/InnerApi/Requests/GetExitSurveyRequest.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/InnerApi/Responses/ApprenticeFeedbackTarget.cs
src/ApprenticeFeedback/SFA.DAS.ApprenticeFeedback/Models/ApprenticeExitSurvey.cs

New exit survey endpoint calling inner api

QF-465 Exit Interview

---

src/ApimDeveloper/SFA.DAS.ApimDeveloper.Api.UnitTests/AppStart/WhenAddingServicesToTheContainer.cs
src/ApimDeveloper/SFA.DAS.ApimDeveloper.Api/AppStart/AddServiceRegistrationExtensions.cs
src/ApimDeveloper/SFA.DAS.ApimDeveloper.UnitTests/Application/EmployerAccounts/WhenHandlingGetAccountsQuery.cs
src/ApimDeveloper/SFA.DAS.ApimDeveloper/Application/EmployerAccounts/Queries/GetAccountsQueryHandler.cs
src/Reservations/SFA.DAS.Reservations.Api.UnitTests/AppStart/WhenAddingServicesToTheContainer.cs
src/Reservations/SFA.DAS.Reservations.Api.UnitTests/Controllers/EmployerAccounts/WhenGettingEmployerAccounts.cs
src/Reservations/SFA.DAS.Reservations.Api.UnitTests/Models/WhenCastingGetUserAccountsApiResponseFromMediatorType.cs
src/Reservations/SFA.DAS.Reservations.Api/AppStart/AddConfigurationOptionsExtension.cs
src/Reservations/SFA.DAS.Reservations.Api/AppStart/AddServiceRegistrationExtension.cs
src/Reservations/SFA.DAS.Reservations.Api/Controllers/AccountUsersController.cs
src/Reservations/SFA.DAS.Reservations.Api/Models/GetUserAccountsApiResponse.cs
src/Reservations/SFA.DAS.Reservations.Api/SFA.DAS.Reservations.Api.csproj
src/Reservations/SFA.DAS.Reservations.UnitTests/Application/AccountUsers/WhenHandlingGetAccountsQuery.cs
src/Reservations/SFA.DAS.Reservations/Application/AccountUsers/AccountUser.cs
src/Reservations/SFA.DAS.Reservations/Application/AccountUsers/Queries/GetAccountsQuery.cs
src/Reservations/SFA.DAS.Reservations/Application/AccountUsers/Queries/GetAccountsQueryHandler.cs
src/Reservations/SFA.DAS.Reservations/Application/AccountUsers/Queries/GetAccountsQueryResult.cs
src/Reservations/SFA.DAS.Reservations/SFA.DAS.Reservations.csproj
src/Shared/SFA.DAS.SharedOuterApi.UnitTests/InnerApi/Requests/WhenBuildingGetAccountTeamMembersRequest.cs
src/Shared/SFA.DAS.SharedOuterApi.UnitTests/InnerApi/Requests/WhenBuildingGetUserAccountsRequest.cs
src/Shared/SFA.DAS.SharedOuterApi.UnitTests/Services/EmployerAccountsServiceTests/WhenGettingEmployerAccountsTests.cs
src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Requests/GetAccountTeamMembersRequest.cs
src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Requests/GetUserAccountsRequest.cs
src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/EmployerUsersApiResponse.cs
src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/GetAccountTeamMembersResponse.cs
src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/GetUserAccountsResponse.cs
src/Shared/SFA.DAS.SharedOuterApi/Models/EmployerAccountUser.cs
src/Shared/SFA.DAS.SharedOuterApi/Models/EmployerProfile.cs
src/Shared/SFA.DAS.SharedOuterApi/Services/EmployerAccountsService.cs

FAI-626 Gov sign in for Reservations web

---

src/Funding/azure-pipelines.yml

Changes made to conform to standard set in other outer pipeline triggers

Removed src/Shared path trigger from Funding

---

src/Recruit/SFA.DAS.Recruit.Api.UnitTests/Controllers/Providers/WhenGettingAllProviders.cs
src/Recruit/SFA.DAS.Recruit.Api.UnitTests/Models/WhenMappingGetProviderAddressFromMediatorType.cs
src/Recruit/SFA.DAS.Recruit.Api.UnitTests/Models/WhenMappingGetProviderResponseFromMediatorType.cs
src/Recruit/SFA.DAS.Recruit.Api/AppStart/AddConfigurationOptionsExtension.cs
src/Recruit/SFA.DAS.Recruit.Api/AppStart/AddServiceRegistrationExtension.cs
src/Recruit/SFA.DAS.Recruit.Api/Models/GetProviderAddress.cs
src/Recruit/SFA.DAS.Recruit.Api/Startup.cs
src/Recruit/SFA.DAS.Recruit.UnitTests/Application/Queries/GetProviders/WhenHandlingTheGetProvidersQuery.cs
src/Recruit/SFA.DAS.Recruit.sln
src/Recruit/SFA.DAS.Recruit/Application/Queries/GetProviders/GetProvidersQueryHandler.cs
src/Recruit/SFA.DAS.Recruit/InnerApi/Responses/GetProvidersListItemAddress.cs
src/Recruit/SFA.DAS.Recruit/InnerApi/Responses/GetProvidersListResponse.cs

CSP-544 all providers endpoint changed from course delivery to Roatp V2

---

src/VacanciesManage/SFA.DAS.VacanciesManage.Api/Models/CreateVacancyRequest.cs
src/VacanciesManage/SFA.DAS.VacanciesManage/InnerApi/Requests/PostVacancyRequestData.cs

Story: https://skillsfundingagency.atlassian.net/browse/FAI-763
Updated the Swagger definition and Developer APIM documentation

Add Additional Questions to the APIs Swagger Definition

---

src/ApprenticeAan/SFA.DAS.ApprenticeAan.Api.UnitTests/Controllers/ApprenticesControllerTests/CreateApprenticeMemberTests.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Api.UnitTests/Controllers/LocationsControllerTests.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Api/Controllers/ApprenticesController.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Api/Controllers/LocationsController.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Application.UnitTests/Apprentices/Commands/CreateApprenticeMember/CreateApprenticeMemberCommandHandlerTests.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Application/Apprentices/Commands/CreateApprenticeMember/CreateApprenticeMemberCommand.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Application/Apprentices/Commands/CreateApprenticeMember/CreateApprenticeMemberCommandHandler.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Application/InnerApi/Apprentices/PostApprenticeRequest.cs

Also fixed a minor issue in the locations endpoint where I was returning not found response wrongly. Now it just returns ok response with empty results.

CSP-789 Implements create apprentice endpoint

---

src/Approvals/SFA.DAS.Approvals.Api.UnitTests/Models/WhenMappingGetStandardResponseFromMediatorResponse.cs
src/Approvals/SFA.DAS.Approvals.Api/Models/GetStandardResponse.cs
src/Approvals/SFA.DAS.Approvals/InnerApi/Responses/GetStandardsListItem.cs

Updated GetStandardResponse to include Route field

CSP-615 Included Sector into Approvals Standards Daily Cache

---

src/ApprenticeAan/SFA.DAS.ApprenticeAan.Api.UnitTests/Services/QueryStringParameterBuilderTests.cs
src/ApprenticeAan/SFA.DAS.ApprenticeAan.Application/Services/QueryStringParameterBuilder.cs

CSP-918 Get Calendar Events isactive as true

---

src/AdminAan/azure-pipelines.yml

Admin aan outer api setup

---

src/EmployerAan/SFA.DAS.EmployerAan.UnitTests/Application/Employer/Queries/GetEmployerMemberSummary/GetEmployerMemberSummaryQueryHandlerTests.cs
src/EmployerAan/SFA.DAS.EmployerAan/Application/Employer/Queries/GetEmployerMemberSummary/GetEmployerMemberSummaryQueryHandler.cs
src/EmployerAan/SFA.DAS.EmployerAan/Application/Employer/Queries/GetEmployerMemberSummary/GetEmployerMemberSummaryQueryResult.cs

Removed StartDate from GetEmployerMemberSummary

CSP-934 Employer OnBoarding Corrections

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api.UnitTests/Models/WhenMappingFromGetSearchApprenticeshipsModelToSearchApprenticeshipsQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api.UnitTests/Models/WhenMappingFromMediatrResultToSearchApprenticeshipsApiResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/GetSearchApprenticeshipsModel.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/LevelApiResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/SearchApprenticeshipsApiResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/WhenHandlingSearchApprenticeshipsQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Requests/WhenBuildingGetVacanciesRequest.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchApprenticeships/SearchApprenticeshipsQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchApprenticeships/SearchApprenticeshipsQueryHandler.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchApprenticeships/SearchApprenticeshipsResult.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/Requests/GetVacanciesRequest.cs
src/Shared/SFA.DAS.SharedOuterApi.UnitTests/InnerApi/Requests/WhenBuildingGetLevelsListRequest.cs
src/Shared/SFA.DAS.SharedOuterApi.UnitTests/Services/WhenGettingCourseLevels.cs
src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Requests/GetLevelsListRequest.cs
src/Shared/SFA.DAS.SharedOuterApi/InnerApi/Responses/GetLevelsListResponse.cs
src/Shared/SFA.DAS.SharedOuterApi/Interfaces/ICourseService.cs
src/Shared/SFA.DAS.SharedOuterApi/Services/CourseService.cs

Story: https://skillsfundingagency.atlassian.net/browse/FAI-962

Changes related to Levels Filters

---

Directory.Packages.props
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api.UnitTests/Controllers/JobsController/WhenPostingUpdateJob.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api.UnitTests/Controllers/VacanciesController/WhenGetVacancyByVacancyReference.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Controllers/JobsController.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Commands/Apply/WhenHandlingUpdateJobCommand.cs

Downgrading the MOQ version in the shared project as this breaks unit testing in FindApprenticeshipTraining

Downgrading/Reverting the MOQ version in the shared project

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api.UnitTests/Models/WhenMappingFromMediatrResultToSearchApprenticeshipsApiResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Controllers/VacanciesController.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/GetApprenticeshipVacancyApiResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/GetSearchApprenticeshipsModel.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/GetVacanciesListResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/SearchByVacancyReference/WhenHandlingGetApprenticeshipVacancyQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/WhenHandlingSearchApprenticeshipsQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchApprenticeships/SearchApprenticeshipsQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchApprenticeships/SearchApprenticeshipsQueryHandler.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchByVacancyReference/GetApprenticeshipVacancyQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchByVacancyReference/GetApprenticeshipVacancyQueryHandler.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/SearchByVacancyReference/GetApprenticeshipVacancyQueryResult.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/CandidateApi/Requests/GetApplicationByReferenceApiRequest.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/CandidateApi/Responses/GetApplicationByReferenceApiResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/Responses/GetVacanciesResponse.cs

Added extra properties for Search Results and Get Vacancy Details by reference
Story: https://skillsfundingagency.atlassian.net/browse/FAI-1213

FAI-1213 Added extra properties for Search Results and Get Vacancy Details

---

src/EmployerPR/SFA.DAS.EmployerPR.Api.UnitTests/Controllers/PermissionsControllerTests/PostPermissionsTests.cs
src/EmployerPR/SFA.DAS.EmployerPR.Api/Controllers/PermissionsController.cs
src/EmployerPR/SFA.DAS.EmployerPR.UnitTests/Application/Permissions/Commands/PostPermissions/PostPermissionsCommandHandlerTests.cs
src/EmployerPR/SFA.DAS.EmployerPR/Application/Commands/PostPermissions/PostPermissionsCommand.cs
src/EmployerPR/SFA.DAS.EmployerPR/Application/Commands/PostPermissions/PostPermissionsCommandHandler.cs
src/EmployerPR/SFA.DAS.EmployerPR/Application/Commands/PostPermissions/PostPermissionsCommandResult.cs
src/EmployerPR/SFA.DAS.EmployerPR/Infrastructure/IProviderRelationshipsApiRestClient.cs

- New endpoint as a pass through for the PostPermissions endpoint on CSP-1392.

CSP-1411 - Post Permissions Endpoint.

---

src/Shared/SFA.DAS.SharedOuterApi/Services/EmployerAccountsService.cs

Parallelise to fix timeout issue

Con 5252 get user accounts timeout

---

src/ApprenticeApp/SFA.DAS.ApprenticeApp.Api/AppStart/AddNServiceBusExtension.cs
src/ApprenticeApp/SFA.DAS.ApprenticeApp.Api/SFA.DAS.ApprenticeApp.Api.csproj
src/ApprenticeApp/SFA.DAS.ApprenticeApp.Api/Startup.cs

package updates

---

azure/template.json
pipeline-templates/stage/outerapi-pipeline.yml
src/FindAnApprenticeship/azure-pipelines.yml

**Context**
Now there are multiple APIM endpoint ASP's there needs to be a way to deploy apps to them.
**Proposed Changes**
Add ASP parameter and conditional variable
Few ARM template toolkit alignments
Add FAA variable group so FAA can be added to the new ASP without impacting other applications
**Testing**

DASD-11188 - Add option to define ASP

---

src/Approvals/azure-pipelines.yml
src/EmployerFinance/azure-pipelines.yml
src/FindAnApprenticeship/azure-pipelines.yml
src/LevyTransferMatching/azure-pipelines.yml

Modified triggers so that the required endpoints trigger on all DevOps changes.

removed temporary triggers

---

src/Shared/SFA.DAS.SharedOuterApi.UnitTests/InnerApi/Requests/WhenBuildingGetVacanciesRequest.cs
src/Vacancies/SFA.DAS.Vacancies.UnitTests/InnerApi/Requests/WhenBuildingGetVacancyRequest.cs
src/Vacancies/SFA.DAS.Vacancies/InnerApi/Requests/GetVacancyRequest.cs

Story: https://skillsfundingagency.atlassian.net/browse/FAI-1884

FAI-1884 Internal exception 500 FAA API

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Commands/WhenHandlingPostCandidateAddressCommand.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Commands/WhenHandlingPostManuallyEnteredAddressCommand.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Users/ManuallyEnteredAddress/CreateManuallyEnteredAddressCommandHandler.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Users/SelectedAddress/CreateAddressCommandHandler.cs

Bug: https://skillsfundingagency.atlassian.net/browse/FAI-1817

FAI-1817 Searching invalid Postcode returns 500 internal server exception Error

---

src/EmployerPR/SFA.DAS.EmployerPR.Api.UnitTests/Controllers/RequestsControllerTests/GetRequestTests.cs
src/EmployerPR/SFA.DAS.EmployerPR.Api/Controllers/RequestsController.cs
src/EmployerPR/SFA.DAS.EmployerPR/Application/Queries/GetRequest/GetRequestResponse.cs
src/EmployerPR/SFA.DAS.EmployerPR/Infrastructure/IProviderRelationshipsApiRestClient.cs

- Added a **GetRequest** endpoint to the **RequestsController** in **EmployerPR.Api**.

CSP-1485: Employer PR - RequestsController - Get Request

---

src/FindApprenticeshipJobs/LICENSE
src/FindApprenticeshipJobs/README.md

Story: https://skillsfundingagency.atlassian.net/browse/FAI-1909

FAI-1909 Added License file and ReadMe with useful links

---

src/EmployerRequestApprenticeTraining/SFA.DAS.EmployerRequestApprenticeTraining.Api/Controllers/EmployerRequestsController.cs
src/EmployerRequestApprenticeTraining/SFA.DAS.EmployerRequestApprenticeTraining.UnitTests/Application/Commands/WhenHandlingSendEmployerRequestResponseNotifications.cs
src/EmployerRequestApprenticeTraining/SFA.DAS.EmployerRequestApprenticeTraining/Application/Commands/SendResponseNotification/SendResponseNotificationCommandHandler.cs

ordered titles alphabetically in email content

P2-2227-Email_content_fixes

---

pipeline-templates/job/code-build.yml
pipeline-templates/job/deploy.yml
pipeline-templates/stage/outerapi-pipeline.yml
src/Earnings/azure-pipelines.yml

Added conditional deployment for old das-platform-building-blocks version vs new das-platform-building-blocks version

  Added conditional deployment for old das-platform-building-blocks version vs new das-platform-building-blocks version

---

src/Assessors/azure-pipelines.yml
src/Campaign/azure-pipelines.yml
src/EarlyConnect/azure-pipelines.yml
src/Earnings/azure-pipelines.yml
src/EmployerAan/azure-pipelines.yml

Updated das-platform-building-blocks version for batch 3

Updated das-platform-building-blocks version for batch 3

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api.UnitTests/Controllers/VacanciesController/WhenPostingVacancyDetails.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Controllers/VacanciesController.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.Api/Models/Vacancies/PostApplyApiRequest.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Vacancies/WhenHandlingApplyCommand.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Vacancies/ApplyCommand.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Vacancies/ApplyCommandHandler.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Commands/Vacancies/ApplyCommandResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Vacancies/ApplyCommandResponse.cs

Move Command Handler from Queries to Command section in the SFA.DAS.FindAnApprenticeship.Application

Clean-up Task - Move Command Handler from Queries to Command

---

azure/template.json
src/FindAnApprenticeship/azure-pipelines.yml
src/FindApprenticeshipJobs/azure-pipelines.yml

- Bumped versions of das-platform-building-blocks and das-platform-automation to pick up new script and ARM template.
- Added task/script to retrieve information for the shared application insights and removed old application insights ARM template.
- Added alert for failed requests to ARM template.

added failed requests alert and updated app connection string

---

src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Domain/EmailTemplates/EmailTemplateBuilderTests.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Domain/EmailTemplates/EmailTemplateBuilder.cs

Bug: https://skillsfundingagency.atlassian.net/browse/FAI-2255

FAI-2255 Saved Search Email alert Across England wording change

---

src/Campaign/SFA.DAS.Campaign.UnitTests/InnerApi/Requests/WhenBuildingGetVacanciesRequest.cs
src/Campaign/SFA.DAS.Campaign/InnerApi/Requests/GetVacanciesRequest.cs

Add sort of distance asc for when adverts are searched for from the campaigns website

FAI-2283 - Add sort to get adverts request

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Applications/WhenHandlingGetIndexQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/SavedVacancies/WhenHandlingGetSavedVacanciesQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Applications/GetApplications/GetApplicationsQueryHandler.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/GetSavedVacancies/GetSavedVacanciesQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/Responses/GetVacanciesByReferenceApiResponse.cs

Saved Vacancies & Your Applications page to hold ML

FAI-2232 Saved Vacancies & Your Applications page to hold ML

---

src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api.UnitTests/Controllers/WhenPostingGetSavedSearchResult.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Controllers/SavedSearchesController.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Models/GetCandidateSavedVacanciesRequest.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/SavedSearches/WhenHandlingGetSavedSearchVacanciesQuery.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/SavedSearches/WhenHandlingGetSavedSearchesQueryHandler.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearchVacancies/GetSavedSearchVacanciesQuery.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearchVacancies/GetSavedSearchVacanciesQueryHandler.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearchVacancies/GetSavedSearchVacanciesQueryResult.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearches/GetSavedSearchesQueryHandler.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/SavedSearch/GetSavedSearches/GetSavedSearchesQueryResult.cs

Split out into separate endpoints the getting search alerts, and the running for each candidate

FAI-2304 Search alert bug

---

src/Aodp/SFA.DAS.AODP/Application/Queries/Qualifications/GetNewQualificationsQueryHandler.cs
src/Aodp/SFA.DAS.AODP/Application/Queries/Qualifications/GetNewQualificationsQueryResponse.cs
src/Aodp/SFA.DAS.AODP/Application/Queries/Qualifications/GetQualificationDetailsQueryHandler.cs
src/Aodp/SFA.DAS.AODP/Application/Queries/Qualifications/GetQualificationDetailsQueryResponse.cs
src/Aodp/SFA.DAS.AODP/InnerApi/AodpApi/Qualifications/GetNewQualificationsApiRequest.cs
src/Aodp/SFA.DAS.AODP/InnerApi/AodpApi/Qualifications/GetQualificationDetailsApiRequest.cs
src/Aodp/SFA.DAS.Aodp.Api/Controllers/Qualification/QualificationsController.cs

Controller and CQRS added for Qualifications flow

Qualifications controller and CQRS added

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Services/VacancyService/WhenGettingMultipleVacancies.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/Responses/GetVacanciesByReferenceApiResponse.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Services/VacancyService.cs

- Added new test method in `WhenGettingMultipleVacancies.cs` to handle scenarios where no vacancies are found.
- Modified `OtherAddresses` property in `GetVacanciesByReferenceApiResponse.cs` to filter addresses based on `EmployerLocationOption`.
- Refactored `GetClosedVacancy` method in `VacancyService.cs` to use a helper method for anonymization.
- Updated `GetVacancies` method to efficiently handle cases with no vacancies and ensure proper anonymization of results.
- Overall improvements to code structure and readability.

FAI-2232 Enhance vacancy retrieval and anonymization logic

---

src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingGetLiveVacancy.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/GetLiveVacancyQueryHandler.cs

Add retry for getting live vacancy
Built on top of FAI-2350

FAI-2329 vacancy approved error

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/InnerApi/RecruitApi/Responses/GetClosedVacancyResponse.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Responses/GetLiveVacanciesApiResponse.cs

Reverts SkillsFundingAgency/das-apim-endpoints#2001

Revert "FAI-2275 Enable FAA user accounts to display single location vacancies when deleting account"

---

src/Aodp/SFA.DAS.Aodp/Application/Queries/Qualifications/GetChangedQualificationsQueryResponse.cs

Reflecting changes made to https://github.com/SkillsFundingAgency/das-aodp-api/pull/62#discussion_r1977444768

Updated ChangedQualification domain model 

---

src/Aodp/SFA.DAS.Aodp.Api.UnitTests/Controllers/Qualification/QualificationControllerTests.cs
src/Aodp/SFA.DAS.Aodp.Api/Controllers/Qualification/QualificationsController.cs
src/Aodp/SFA.DAS.Aodp.UnitTests/Application/Queries/Qualification/GetNewQualificationsQueryHandlerTests.cs
src/Aodp/SFA.DAS.Aodp/Application/Extensions/UriExtensions.cs
src/Aodp/SFA.DAS.Aodp/Application/Queries/Jobs/GetJobByNameQueryResponse.cs
src/Aodp/SFA.DAS.Aodp/Application/Queries/Qualifications/GetNewQualificationsQuery.cs
src/Aodp/SFA.DAS.Aodp/Application/Queries/Qualifications/GetNewQualificationsQueryHandler.cs
src/Aodp/SFA.DAS.Aodp/Application/Queries/Qualifications/GetNewQualificationsQueryResponse.cs
src/Aodp/SFA.DAS.Aodp/InnerApi/AodpApi/Jobs/GetJobByNameApiRequest.cs
src/Aodp/SFA.DAS.Aodp/InnerApi/AodpApi/Jobs/GetJobByNameApiResponse.cs
src/Aodp/SFA.DAS.Aodp/InnerApi/AodpApi/Jobs/GetNewQualificationsApiResponse.cs
src/Aodp/SFA.DAS.Aodp/InnerApi/AodpApi/Qualifications/GetNewQualificationsApiRequest.cs

AWARD-79 New Qualifications outer api calls

Award 79 qualification review new qualifications

---

Directory.Packages.props
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingGetLiveVacancy.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Application/WhenHandlingProcessVacancyClosedEarlyCommand.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/InnerApi/WhenBuildingGetClosedVacancyApiRequest.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Commands/ProcessVacancyClosedEarlyCommandHandler.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Queries/GetLiveVacancyQueryHandler.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Requests/GetClosedVacancyApiRequest.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Requests/GetLiveVacancyApiRequest.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Responses/GetClosedVacancyApiResponse.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/InnerApi/Responses/GetLiveVacancyApiResponse.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.csproj

Handle vacancy closed and vacancy approved event issues

FAI-2350 FAI-2328 FAI-2329

---

src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.Api/Models/GetLiveVacanciesApiResponse.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs.UnitTests/Services/WhenMappingLiveVacancy.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Application/Shared/LiveVacancy.cs
src/FindApprenticeshipJobs/SFA.DAS.FindApprenticeshipJobs/Services/LiveVacancyMapper.cs

Map other addresses through to vacancy updated handler so ML addresses are correctly updated

FAI-2414 - Map through OtherAddresses

---

src/Aodp/SFA.DAS.Aodp.Api.UnitTests/Controllers/Qualification/QualificationControllerTests.cs

fixed qualificationcontroller tests

fix of tests

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Apply/WhenHandlingGetIndexQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Apply/Index/GetIndexQueryHandler.cs

Fix issue when there is only a question 2 - This should always go in the question 2 id and text so the status is correct

FAI-2433 - Fix issue with additional question ordering

---

src/FindApprenticeshipTraining/SFA.DAS.FindApprenticeshipTraining/Application/Courses/Queries/GetCourseProvider/GetCourseProviderQueryHandler.cs

- Refactor the **GetCourseProviderQueryHandler** so that specific requests run in parallel.

CSP-1692: Refactor Training providers details endpoint to fetch data parallelly 

---

src/AdminAan/azure-pipelines.yml
src/AparRegister/azure-pipelines.yml
src/EmployerAan/azure-pipelines.yml
src/EmployerPR/azure-pipelines.yml
src/FindApprenticeshipTraining/azure-pipelines.yml
src/ProviderPR/azure-pipelines.yml
src/Roatp/azure-pipelines.yml
src/RoatpCourseManagement/azure-pipelines.yml
src/RoatpOversight/azure-pipelines.yml
src/RoatpProviderModeration/azure-pipelines.yml

Upgraded the following to das-platform-building-blocks:
AparRegister
EmployerPR
FindApprenticeshipTraining
ProviderPR
Roatp
RoatpCourseManagement
RoatpOversight
RoatpProviderModeration
AdminAan
EmployerAan

Csp 1993 upgrade to sonar cloud v3

---

src/VacanciesManage/SFA.DAS.VacanciesManage/InnerApi/Requests/PostVacancyRequestData.cs

Add missing enum type for competitive salary

FAI-2529 - Fix Post Vacancy with competitive salary

---

Directory.Packages.props
src/Campaign/SFA.DAS.Campaign.Api.UnitTests/Models/WhenMappingGetAdvertsResponseFromMediatorType.cs

Fixed broken Campaign tests due to changes to Location class in shared

Fixed broken Campaign tests due to changes to Location class in shared

---

src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship.UnitTests/Application/Queries/Applications/WhenHandlingGetAccountDeletionQuery.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Users/GetAccountDeletionQuery/GetAccountDeletionQueryHandler.cs
src/FindAnApprenticeship/SFA.DAS.FindAnApprenticeship/Application/Queries/Users/GetAccountDeletionQuery/GetAccountDeletionQueryResult.cs

- Added `ApprenticeshipType` to `Application` for better data handling.
- Refined application status handling using `nameof` for type safety.
- Replaced `Enum.TryParse` for improved error handling of statuses.
- Updated `using` directives to include shared outer API models.
- Overall improvements in clarity, safety, and functionality.

FAI-2571 Deleting account foundtion apprenticeship

---

src/ApprenticeApp/SFA.DAS.ApprenticeApp.UnitTests/Extensions/ExtensionTests.cs
src/ApprenticeApp/SFA.DAS.ApprenticeApp/Application/Queries/ApprenticeDetails/GetApprenticeDetailsQueryHandler.cs
src/ApprenticeApp/SFA.DAS.ApprenticeApp/Extensions/Extension.cs
src/ApprenticeApp/SFA.DAS.ApprenticeApp/Models/MyApprenticeshipData.cs
src/ApprenticeApp/SFA.DAS.ApprenticeApp/Services/CoursesService.cs

Extension helper made to return null by default
models with apprenticeshipType to allow for nullable values

Apprenticeship type made nullable
